### ISSUE TITLE
general package build issues

### ISSUE THREAD

**Issue by jschaufele** [SharePoint/sp-dev-training-spfx-spcontent#3]
On all of these training demos using react have had issues using npm. I got past these using yarn but then there were errors when running gulp serve.

I created an empty solution using yo with the react framework then backfilled the demos. I found I had to add a couple more packages and ended up with a package.json which has worked from then on... but only using yarn.

I don't have the time or technical know how to understand why yarn works and npm fails or what module was incompatible with another -   just wanted to find a way forward and learn what the demos wanted to teach 

Attached is the package.json file I use in  case you find it helpful

[package.txt](https://github.com/SharePoint/sp-dev-training-spfx-spcontent/files/2736393/package.txt)

**Comment by andrewconnell** [comment]
Thanks... would help if you shared the version of Node & NPM you are using.

**Comment by jschaufele** [comment]
Sure sorry 
node v8.12.0
npm 6.5.0

**Comment by andrewconnell** [comment]
Thanks... while that's what is currently recommended & supported, it's hard to act on it without details on what errors you're seeing. Unfortunately "there were errors" isn't enough to act on. If you can provide more info that would help repro an issue that could be addressed, but as it is, everything seems to be ok as I just did it again with no issues.

I see additional things in the `package.json` that you pasted that aren't referenced anywhere in the module so they weren't necessary (the **@pnp** scoped packages).
